FROM vllm/vllm-openai@sha256:251eba5cc7c12fed0b75da22a9240e582b1c9e39f6fbc064f86781b963bd814f
COPY platform_utils.py /usr/local/lib/python3.12/dist-packages/vllm/utils/platform_utils.py
COPY attn_utils.py /usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu/attn_utils.py
