FROM qwen-vllm:mrv2-a0f6d767-fi0614
COPY platform_utils.py /usr/local/lib/python3.12/dist-packages/vllm/utils/platform_utils.py
COPY attn_utils.py /usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu/attn_utils.py
