services:
  qwen36-a3b-bf16-dflash:
    image: vllm-latest:0.21.0
    container_name: vllm-qwen36-a3b-bf16-dflash
    restart: "no"
    ports:
      - "8000:8000"
    ipc: host
    shm_size: 32g
    volumes:
      - ${HOME}/models:/models
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HF_HOME: /models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      --model /models/hub/models--Qwen--Qwen3.6-35B-A3B/snapshots/995ad96eacd98c81ed38be0c5b274b04031597b0
      --served-model-name Qwen3.6-35B-A3B-BF16-DFLASH
      --host 0.0.0.0
      --port 8000
      --max-model-len 262144
      --gpu-memory-utilization 0.85
      --max-num-batched-tokens 262144
      --speculative-model /models/hub/models--z-lab--Qwen3.6-35B-A3B-DFlash/snapshots/42d3b34d588423cdae7ba8f53a8cf7789346a719
      --num-speculative-tokens 8
      --speculative-algorithm DFLASH
